# Generated by Django 4.0.2 on 2022-02-24 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 11, 47, 32, 227371)),
        ),
    ]
