# Generated by Django 4.0.2 on 2022-02-24 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_task_completed_alter_task_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 24, 14, 55, 47, 711811)),
        ),
    ]
