# Generated by Django 4.0.2 on 2022-03-02 10:50

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_task_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complition_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 2, 13, 50, 35, 705070)),
        ),
    ]
