# Generated by Django 4.0.2 on 2022-03-02 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_task_complition_datetime_alter_task_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complition_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 2, 13, 53, 33, 478738)),
        ),
    ]
